global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'lujain.darwazeh123@gmail.com'
  smtp_auth_username: 'lujain.darwazeh123@gmail.com'
  smtp_auth_password: 'vvyngcllzagkaupy'  




route:
  receiver: 'default-email'
  routes:
    - match:
        alertname: MySQLDown
      receiver: 'combined'
    - match:
        alertname: RedisDown
      receiver: 'combined'
    - match:
        alertname: KafkaDown
      receiver: 'combined'

receivers:
  - name: 'default-email'
    email_configs:
      - to: 'lujain.darwazeh123@gmail.com'
        send_resolved: true

  - name: 'combined'
    email_configs:
      - to: 'lujain.darwazeh123@gmail.com'
        send_resolved: true
    webhook_configs:
      - url: 'http://host.docker.internal:5000/alert'


  