version: "3"



services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./storage/logs:/var/log/laravel 
      - ./storage/tmp_logs:/var/log/laravel/tmp_logs
  
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana-enterprise:12.1.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml 
      - ./prometheus/sd:/etc/prometheus/sd
    depends_on:
      - blackbox
      - alertmanager
    
    networks:
      - monitoring


  


 
  blackbox:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml

    networks:
      - monitoring

  


  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

    networks:
      - monitoring




      

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


networks:
  monitoring:
    external:
      name: monitoring

